/// 学校列表里的一所学校
class SchoolInfo {
  const SchoolInfo({
    required this.name,
    required this.url,
    this.type = '',
    this.verified = false,
  });

  /// 学校名称，会用作课表默认名称
  final String name;

  /// 教务系统入口地址（登录页或统一身份认证页）
  final String url;

  /// 教务系统类型，如 `jwglxt`。目前只作记录：解析是挨个试的，不靠它猜
  final String type;

  /// 是否已经拿真实课表页验证过。没验证过的要如实标出来，
  /// 不能让用户以为「列表里有就一定能用」
  final bool verified;

  /// 搜索匹配：按校名做包含匹配，忽略大小写与空格
  bool matches(String keyword) {
    final query = keyword.replaceAll(RegExp(r'\s+'), '').toLowerCase();
    if (query.isEmpty) return true;
    return name.replaceAll(RegExp(r'\s+'), '').toLowerCase().contains(query);
  }
}

/// 其它学校的列表。
///
/// 这份列表**直接内置在包里，不依赖任何服务器**，因此 App 完全离线也能选学校，
/// 也不会因为某个接口挂了就用不了。
///
/// 收录分两档：
/// - 拿真实课表页验证过能用的，`verified: true`，排在最前面
/// - 从公开的课程表适配仓库整理来的教务系统入口，只保证网址来自真实提交，
///   没验证过能不能解析，一律 `verified: false`，界面上会如实标出来
///
/// 之所以敢收这么多没验证的：解析器覆盖不到的学校，用户还能走「AI 识别导入」
/// 那条路，不至于选完学校就卡死。入口给全一点，用户能少手打一串网址。
///
/// 想加学校或修正网址，请提 issue（模板见仓库 `.github/ISSUE_TEMPLATE/`）。
class SchoolService {
  const SchoolService();

  /// 内置学校列表
  static const List<SchoolInfo> schools = [
    SchoolInfo(
      name: '浙江横店影视职业学院',
      url: 'http://jwgl.hcft.edu.cn/jwglxt/',
      type: 'jwglxt',
      verified: true,
    ),
    SchoolInfo(
      name: '湖州职业技术学院',
      url: 'https://cas.huvtc.edu.cn/login?service=https%3A%2F%2Fcas.huvtc.edu.cn%2Fapi%2Fblade-auth%2Fcas%2FcreateTicket%3Fservice%3Dhttp%3A%2F%2Fjwxt.huvtc.edu.cn%2Fjwglxt%2Fxtgl%2Findex_initMenu.html',
      type: 'jwglxt',
      verified: true,
    ),
    SchoolInfo(name: '北部湾大学', url: 'https://zhjw.bbgu.edu.cn/workspace/home'),
    SchoolInfo(name: '北京邮电大学', url: 'https://jwgl.bupt.edu.cn/jsxsd/'),
    SchoolInfo(name: '重庆大学', url: 'https://my.cqu.edu.cn/'),
    SchoolInfo(name: '重庆交通大学', url: 'https://jwgln.cqjtu.edu.cn/jsxsd/sso.jsp'),
    SchoolInfo(name: '重庆城市科技学院', url: 'http://jw.cqcst.edu.cn/cqdxcskjxy_jsxsd/'),
    SchoolInfo(name: '重庆理工大学', url: 'https://timetable-cfc.cqut.edu.cn/'),
    SchoolInfo(name: '重庆科技大学', url: 'https://web.cqust.edu.cn/'),
    SchoolInfo(name: '重庆工商职业学院', url: 'http://szxy.cqtbi.edu.cn/cqdddt/index.html?v=0.3672285490800563'),
    SchoolInfo(name: '长春理工大学', url: 'https://mysso.cust.edu.cn/cas/login?service=https://jwgl.cust.edu.cn/welcome'),
    SchoolInfo(name: '成都信息工程大学', url: 'https://ywtb.cuit.edu.cn/'),
    SchoolInfo(name: '成都中医药大学', url: 'https://jwweb.cdutcm.edu.cn/'),
    SchoolInfo(name: '上海中侨职业技术大学', url: 'https://cas.shzq.edu.cn/cas/login?service=https://jw.shzq.edu.cn/sso/ddlogin'),
    SchoolInfo(name: '湖南三一工业职业技术学院', url: 'https://ehall.sanyedu.com/new/index.html'),
    SchoolInfo(name: '河南职业技术学院', url: 'https://one.hnzj.edu.cn/common-service/kcb-pc/personage/personage'),
    SchoolInfo(name: '济源职业技术学院', url: 'https://jwgl.jyvtc.edu.cn/jyvtcjw/'),
    SchoolInfo(name: '云南财经大学', url: 'https://xjwis.ynufe.edu.cn/jsxsd/'),
    SchoolInfo(name: '河南师范大学', url: 'https://jwc.htu.edu.cn/'),
    SchoolInfo(name: '河南科技学院', url: 'http://jwgl.hist.edu.cn/cas/login.action'),
    SchoolInfo(name: '淮南师范学院', url: 'https://xxmh.hnnu.edu.cn/zhxy/'),
    SchoolInfo(name: '塔里木大学', url: 'https://auth.taru.edu.cn/cas/login?service=https%3A%2F%2Fhall.taru.edu.cn%2FserviceHall'),
    SchoolInfo(name: '马鞍山学院', url: 'https://jwxt.masu.edu.cn/'),
    SchoolInfo(name: '茂名职业技术学院', url: 'https://jwc.mmpt.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '绵阳师范学院', url: 'http://jw.mtc.edu.cn/'),
    SchoolInfo(name: '闽南科技学院', url: 'https://jwgl.mku.edu.cn/'),
    SchoolInfo(name: '西南交通大学', url: 'https://yhxt.swjtu.edu.cn/study/teach/course/stu-course-list'),
    SchoolInfo(name: '山西工程职业学院', url: 'https://sxevc.jw.chaoxing.com/admin/login'),
    SchoolInfo(name: '西安文理学院', url: 'http://jwgl.xawl.edu.cn/jwglxt/', type: 'jwglxt'),
    SchoolInfo(name: '湖南商务职业技术学院', url: 'http://jwxt.hnvcc.edu.cn/'),
    SchoolInfo(name: '湖南邮电职业技术学院', url: 'http://jx.hnxyjf.com:10081/jsxsd/'),
    SchoolInfo(name: '内蒙古工业大学', url: 'http://jw.imut.edu.cn/academic/login/imut/loginIds6Valid.jsp'),
    SchoolInfo(name: '喀什大学', url: 'https://cas.ksu.edu.cn/cas/login?service=https://jwnet.ksu.edu.cn/sso/ddlogin'),
    SchoolInfo(name: '武汉船舶职业技术学院', url: 'http://jw.wspc.edu.cn/jwapp/sys/wdkb/*default/index.do?EMAP_LANG=zh#/xskcb'),
    SchoolInfo(name: '三峡大学', url: 'http://jwxt.ctgu.edu.cn/jwapp/sys/yjsrzfwapp/dbLogin/main.do'),
    SchoolInfo(name: '江西理工大学', url: 'https://authserver.jxust.edu.cn/authserver/login?service=https://jw.jxust.edu.cn/jsxsd/'),
    SchoolInfo(name: '广州松田职业学院', url: 'https://jw.educationgroup.cn/gzstzyxy_jsxsd/'),
    SchoolInfo(name: '福建船政交通职业学院', url: 'https://webvpn.fjcpc.edu.cn/'),
    SchoolInfo(name: '福建农林大学', url: 'http://jwgl.fafu.edu.cn/'),
    SchoolInfo(name: '福建信息职业技术学院', url: 'https://jw.fjpit.com/#/auth/login'),
    SchoolInfo(name: '佛山大学', url: 'https://100.fosu.edu.cn/'),
    SchoolInfo(name: '山东药品食品职业学院', url: 'http://cas.sddfvc.edu.cn/login?type=usernamepassword&service=http%3A%2F%2Ffazhan.sddfvc.edu.cn%2Fjs%2Ffzzx%2Flogin'),
    SchoolInfo(name: '山东轻工职业学院', url: 'https://crp.sdlivc.cn/xsgl/xs/login/login.aspx'),
    SchoolInfo(name: '重庆化工职业学院', url: 'http://dc.cqcivc.cn/cas/login?service=http://jwxt.cqcivc.edu.cn/sso/zllogin'),
    SchoolInfo(name: '东北大学', url: 'http://jwxt.neu.edu.cn/'),
    SchoolInfo(name: '东北大学（研究生）', url: 'https://yjs.neu.edu.cn/'),
    SchoolInfo(name: '南京师范大学', url: 'https://authserver.nnu.edu.cn/authserver/login?service=https://hsnnu.nnu.edu.cn/login'),
    SchoolInfo(name: '南京邮电大学', url: 'https://i.njupt.edu.cn/'),
    SchoolInfo(name: '南京航空航天大学', url: 'https://aao-eas.nuaa.edu.cn/eams/login.action'),
    SchoolInfo(name: '厦门城市职业学院', url: 'https://eone-443.webvpn.xmcu.edu.cn/'),
    SchoolInfo(name: '徐州工程学院', url: 'http://jwglxt.xzit.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '淮北理工学院', url: 'https://a.hblgxy.edu.cn:5111/jsxsd/'),
    SchoolInfo(name: '新疆工程学院', url: 'https://authserver.xjie.edu.cn/authserver/login?service=https%3A%2F%2Fjwxt.xjie.edu.cn%2Fjsxsd%2F'),
    SchoolInfo(name: '广东药科大学', url: 'https://webvpn.gdpu.edu.cn/https/77726476706e69737468656265737421f3f652d220347845300d8db9d6562d/lyuapServer/login?service=https%3A%2F%2Fjwsys.gdpu.edu.cn%2Fsso%2Flyiotlogin'),
    SchoolInfo(name: '广东工业大学', url: 'https://authserver.gdut.edu.cn/authserver/login?service=https%3A%2F%2Fjxfw.gdut.edu.cn%2Fnew%2FssoLogin'),
    SchoolInfo(name: '湖南科技大学', url: 'https://kdjw.hnust.edu.cn/'),
    SchoolInfo(name: '湖南科技学院', url: 'http://jw.huse.cn/jsxsd'),
    SchoolInfo(name: '华中科技大学', url: 'http://mhub.hust.edu.cn'),
    SchoolInfo(name: '江苏师范大学', url: 'https://i.jsnu.edu.cn/home'),
    SchoolInfo(name: '江西飞行学院', url: 'https://jwxt.jxfu.edu.cn/'),
    SchoolInfo(name: '东北农业大学', url: 'https://webvpn.neau.edu.cn/'),
    SchoolInfo(name: '苏州大学', url: 'http://xk.suda.edu.cn/'),
    SchoolInfo(name: '重庆人文科技学院', url: 'https://https-auth-cqrk-edu-cn-443.webvpn.cqrk.edu.cn:8480/cas/login?service=http%3A%2F%2Fportal.cqrk.edu.cn&rewrite=1'),
    SchoolInfo(name: '武汉商学院', url: 'https://jwxt.wbu.edu.cn/'),
    SchoolInfo(name: '东北师范大学', url: 'https://bkjx.nenu.edu.cn/'),
    SchoolInfo(name: '河南工业大学', url: 'https://jwglxt.haut.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '宿州学院', url: 'http://211.86.128.194/suzxyjw/cas/login.action'),
    SchoolInfo(name: '西安理工大学', url: 'http://jwgl.xaut.edu.cn/'),
    SchoolInfo(name: '湖北汽车工业学院', url: 'https://cas.huat.edu.cn/authserver/login?service=http%3A%2F%2Fneweas.huat.edu.cn%2Flogin'),
    SchoolInfo(name: '中国石油大学(北京)', url: 'https://bk.cup.edu.cn/student/'),
    SchoolInfo(name: '中国石油大学(北京)（研究生）', url: 'https://gmis.cup.edu.cn/gmis/student/default/index'),
    SchoolInfo(name: '仲恺农业工程学院', url: 'https://edu-admin.zhku.edu.cn/'),
    SchoolInfo(name: '广西电力职业技术学院', url: 'https://jw.gxdlxy.com/jsxsd/framework/xsMain.jsp'),
    SchoolInfo(name: '长江大学', url: 'https://cas-yangtzeu-edu-cn.atrust.yangtzeu.edu.cn/authserver/login?service=https%3A%2F%2Fatrust.yangtzeu.edu.cn%3A4443%2Fpassport%2Fv1%2Fauth%2Fcas%3FsfDomain%3DCAS'),
    SchoolInfo(name: '成都航空职业技术大学', url: 'https://jwxt.cap.edu.cn/jwapp/sys/homeapp/home/index.html?av=&contextPath=/jwapp#/'),
    SchoolInfo(name: '甘肃医学院', url: 'https://jw.gsmc.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '天津城建大学', url: 'https://authserver.tcu.edu.cn/authserver/login?service=https%3A%2F%2Fjwxs.tcu.edu.cn%2Flogin'),
    SchoolInfo(name: '天津科技大学', url: 'https://id.tust.edu.cn/authserver/login?service=http://jwxtxs.tust.edu.cn:46110/j_spring_cas_security_check'),
    SchoolInfo(name: '华南理工大学', url: 'http://xsjw2018.jw.scut.edu.cn/'),
    SchoolInfo(name: '衡阳师范学院', url: 'https://hysfjw.hynu.edu.cn/jsxsd/'),
    SchoolInfo(name: '暨南大学', url: 'https://jw.jnu.edu.cn'),
    SchoolInfo(name: '华侨大学', url: 'https://atrust.hqu.edu.cn/portal/?redirectid=0.6668972084789097#/login'),
    SchoolInfo(name: '济南大学', url: 'https://sso.ujn.edu.cn/tpass/login?service=http%3A%2F%2Fjwgl.ujn.edu.cn%2Fsso%2Fdriotlogin'),
    SchoolInfo(name: '济宁医学院', url: 'http://210.44.16.13/'),
    SchoolInfo(name: '河北地质大学华信学院', url: 'http://61.182.88.214:8090'),
    SchoolInfo(name: '成都银杏酒店管理学院', url: 'http://zfjw.gingkoc.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '湖南信息职业技术学院', url: 'https://authserver.hniu.cn/authserver/login?service=https%3A%2F%2Fehall.hniu.cn%3A443%2Flogin%3Fservice%3Dhttps%3A%2F%2Fehall.hniu.cn%2Fnew%2Findex.html%3Fbrowser%3Dno%25EF%25BC%2589#StudentAffairsA'),
    SchoolInfo(name: '河南财经政法大学', url: 'https://xk.huel.edu.cn'),
    SchoolInfo(name: '桂林医科大学', url: 'https://ejwc.glmc.edu.cn/'),
    SchoolInfo(name: '广西医科大学', url: 'https://cas.gxmu.edu.cn/lyuapServer/login'),
    SchoolInfo(name: '南京林业大学', url: 'https://jwxt.njfu.edu.cn/sso.jsp'),
    SchoolInfo(name: '桂林信息科技学院', url: 'https://172-16-18-132.webvpn.guit.edu.cn'),
    SchoolInfo(name: '大连海事大学', url: 'http://jw.xpaas.dlmu.edu.cn/eams'),
    SchoolInfo(name: '河南信息科技学院', url: 'http://39.164.230.243:9527/#/authserver/login?redirect_uri=aHR0cDovLzM5LjE2NC4yMzAuMjQzOjkxL2VhbXMvbG9naW4uYWN0aW9u'),
    SchoolInfo(name: '东北大学秦皇岛分校', url: 'https://jwxt.neuq.edu.cn'),
    SchoolInfo(name: '江苏大学', url: 'https://jwxt.ujs.edu.cn/sso/jziotlogin'),
    SchoolInfo(name: '江苏大学（研究生）', url: 'http://yjsgll.ujs.edu.cn/pyxx/'),
    SchoolInfo(name: '重庆电子科技职业大学', url: 'https://cquet.edu.cn/'),
    SchoolInfo(name: '宜宾学院', url: 'https://authserver.yibinu.edu.cn/authserver/login?service=https://ehall.yibinu.edu.cn:443/login?service=https://ehall.yibinu.edu.cn/new/index.html'),
    SchoolInfo(name: '大连大学', url: 'https://webvpn.dlu.edu.cn/login'),
    SchoolInfo(name: '湖北医药学院', url: 'https://jw.hbmu.edu.cn/'),
    SchoolInfo(name: '湖北民族大学', url: 'https://jwgl.hbmzu.edu.cn/edu/'),
    SchoolInfo(name: '湖北文理学院', url: 'https://hbuas.jw.chaoxing.com/admin/login'),
    SchoolInfo(name: '同济大学', url: 'https://1.tongji.edu.cn/'),
    SchoolInfo(name: '山东师范大学', url: 'http://jwxt.sdnu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '中国石油大学（北京）克拉玛依校区', url: 'https://eams.cupk.edu.cn/student/'),
    SchoolInfo(name: '宁波工程学院', url: 'http://jwxt.nbut.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '山东华宇工学院', url: 'http://jwgl.huayu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '泰山学院', url: 'http://jwxt.tsu.edu.cn'),
    SchoolInfo(name: '广东轻工职业技术大学', url: 'https://jw.gdipu.edu.cn'),
    SchoolInfo(name: '中南民族大学', url: 'https://webvpn.scuec.edu.cn/'),
    SchoolInfo(name: '枣庄学院', url: 'https://iam.uzz.edu.cn/esc-sso/login/page'),
    SchoolInfo(name: '成都医学院', url: 'https://jwweb.cmc.edu.cn/'),
    SchoolInfo(name: '山东石油化工学院', url: 'https://webvpn.sdipct.edu.cn/https/77726476706e69737468656265737421fae0598869236c596e0b9de29d51367bd943/'),
    SchoolInfo(name: '广东科技学院', url: 'https://webvpn.gdust.edu.cn/https/77726476706e69737468656265737421f3f652d220347d436a468ca88d1b203b/cas/?service=https%3A%2F%2Fwebvpn.gdust.edu.cn%2Flogin%3Fcas_login%3Dtrue'),
    SchoolInfo(name: '中国石油大学(华东)', url: 'https://webvpn.upc.edu.cn/users/sign_in'),
    SchoolInfo(name: '中国石油大学(华东)（研究生）', url: 'https://degrees.upc.edu.cn/'),
    SchoolInfo(name: '天津农学院', url: 'http://jwxt.tjau.edu.cn/eams/homeExt.action'),
    SchoolInfo(name: '长春工程学院', url: 'https://webvpn.ccit.edu.cn/auth/login'),
    SchoolInfo(name: '呼和浩特民族学院', url: 'http://211.82.176.48/academic/login/imnc/loginIds6.jsp'),
    SchoolInfo(name: '北方工业大学', url: 'https://jwxtbk.ncut.edu.cn/jsxsd/'),
    SchoolInfo(name: '江西师范大学', url: 'https://jwc.jxnu.edu.cn/'),
    SchoolInfo(name: '南昌航空大学科技学院', url: 'http://qzjwxt.stcnchu.edu.cn:800/jsxsd/'),
    SchoolInfo(name: '重庆财经学院', url: 'http://jwmis.cfec.edu.cn/jwglxt/kbcx/xskbcx_cxXskbcxIndex.html?gnmkdm=N2151&layout=default', type: 'jwglxt'),
    SchoolInfo(name: '安徽中医药高等专科学校', url: 'https://authserver.ahzyygz.edu.cn/authserver/login?service=http://jwxt.ahzyygz.edu.cn/ahzyygzjw/caslogin'),
    SchoolInfo(name: '西安工业大学', url: 'http://jwgl2018.xatu.edu.cn'),
    SchoolInfo(name: '西北工业大学', url: 'https://ecampus.nwpu.edu.cn/'),
    SchoolInfo(name: '南京工业大学', url: 'https://jwgl.njtech.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '南京信息工程大学', url: 'https://jwxt.nuist.edu.cn/'),
    SchoolInfo(name: '中国民航大学', url: 'https://http-jwgl-cauc-edu-cn-80.webvpn.cauc.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '大连工程学院', url: 'https://jw.dlutci.edu.cn'),
    SchoolInfo(name: '德州学院', url: 'http://211.64.47.165/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '华东交通大学', url: 'https://jwxt.ecjtu.edu.cn/index.action'),
    SchoolInfo(name: '文华学院', url: 'https://jw1.hustwenhua.net/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '信阳农林学院', url: 'https://sso.xyafu.edu.cn/sso/login?service=https%3A%2F%2Fjwgl.xyafu.edu.cn%2Fcaslogin'),
    SchoolInfo(name: '新疆政法学院', url: 'https://jwxt.xjzfu.edu.cn/jwapp/sys/homeapp/home/index.html'),
    SchoolInfo(name: '浙江工业大学', url: 'http://www.gdjw.zjut.edu.cn/jwglxt/xtgl/login_slogin.html?kickout=1', type: 'jwglxt'),
    SchoolInfo(name: '合肥师范学院', url: 'https://jw.hfnu.edu.cn/eams/loginExt.action'),
    SchoolInfo(name: '郑州航空工业管理学院', url: 'http://jwglxt.zua.edu.cn/eams/loginExt.action', type: 'jwglxt'),
    SchoolInfo(name: '江西航空职业技术学院', url: 'https://jw.jhzyedu.cn/xtgl/login_slogin.html?ydType=0'),
    SchoolInfo(name: '齐齐哈尔工程学院', url: 'http://tysf.qqhrit.com:20261/cas/login'),
    SchoolInfo(name: '内蒙古大学', url: 'https://jwxt.imu.edu.cn/login'),
    SchoolInfo(name: '齐齐哈尔大学', url: 'https://webvpn.qqhru.edu.cn/users/sign_in'),
    SchoolInfo(name: '四川师范大学', url: 'http://202.115.194.60/'),
    SchoolInfo(name: '铜仁学院', url: 'https://gztrc.edu.cn:17232/'),
    SchoolInfo(name: '贵州大学', url: 'https://zhjw.gzu.edu.cn/jwglxt/xtgl/', type: 'jwglxt'),
    SchoolInfo(name: '浙江中医药大学', url: 'https://jwmk.zcmu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '青岛农业大学', url: 'http://jwglxt.qau.edu.cn/', type: 'jwglxt'),
    SchoolInfo(name: '湖南师范大学', url: 'https://jwglnew.hunnu.edu.cn/eams/courseTableForStd.action'),
    SchoolInfo(name: '武汉理工大学', url: 'https://jwxt.whut.edu.cn/'),
    SchoolInfo(name: '中国计量大学', url: 'https://jwxt.cjlu.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '常州机电职业技术学院', url: 'https://webapp.czimt.edu.cn'),
    SchoolInfo(name: '甘肃财贸职业学院', url: 'https://jwxt.gscmxy.edu.cn/'),
    SchoolInfo(name: '青岛理工大学', url: 'https://jxgl.qut.edu.cn/jwglxt/xtgl/index_initMenu.html', type: 'jwglxt'),
    SchoolInfo(name: '中南林业科技大学', url: 'https://webvpn.csuft.edu.cn/'),
    SchoolInfo(name: '吉林大学', url: 'https://iedu.jlu.edu.cn/'),
    SchoolInfo(name: '中国科学技术大学', url: 'https://id.ustc.edu.cn/cas/login?service=https%3A%2F%2Fjw.ustc.edu.cn%2Fucas-sso%2Flogin'),
    SchoolInfo(name: '中国科学技术大学（研究生）', url: 'https://yjs1.ustc.edu.cn/gsapp/sys/yjsrzfwapp/dbLogin/main.do'),
    SchoolInfo(name: '电子科技大学', url: 'https://eams.uestc.edu.cn/eams'),
    SchoolInfo(name: '山东交通学院', url: 'https://wwebvpn.sdjtu.edu.cn'),
    SchoolInfo(name: '广东海洋大学', url: 'https://jw.gdou.edu.cn/'),
    SchoolInfo(name: '广东科学技术职业学院', url: 'https://ids.gdit.edu.cn/authserver/login?service=https://wbdt.gdit.edu.cn/shiro-cas'),
    SchoolInfo(name: '吉利学院', url: 'https://jw.guc.edu.cn/yethan/UserAction?setAction=userLogin'),
    SchoolInfo(name: '南京工业职业技术大学', url: 'https://jwxt.niit.edu.cn/'),
    SchoolInfo(name: '怀化学院', url: 'https://jwmis.hhtc.edu.cn/'),
    SchoolInfo(name: '怀化职业技术学院', url: 'http://jwgl.hhvtc.com.cn/'),
    SchoolInfo(name: '无锡学院', url: 'https://jwgl.cwxu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '黑龙江大学', url: 'http://xsxk.hlju.edu.cn/'),
    SchoolInfo(name: '黑龙江大学（研究生）', url: 'https://yjsglxt.hlju.edu.cn/'),
    SchoolInfo(name: '上海财经大学浙江学院', url: 'https://jwxt.shufe-zj.edu.cn/kbcx/xskbcx_cxXskbcxIndex.html?gnmkdm=N2151&layout=default'),
    SchoolInfo(name: '扬州大学', url: 'https://webvpn.yzu.edu.cn/login'),
    SchoolInfo(name: '西安科技大学', url: 'http://jwsso.xust.edu.cn/frontend/center_portal/home/index.html#/'),
    SchoolInfo(name: '江苏旅游职业学院', url: 'https://authserver.jstc.edu.cn/authserver/login?service=https%3A%2F%2Fjwxt.jstc.edu.cn%2Fstudent%2Fsso%2Flogin'),
    SchoolInfo(name: '广东技术师范大学', url: 'https://jwglxt.gpnu.edu.cn/sso/lyiotlogin', type: 'jwglxt'),
    SchoolInfo(name: '沈阳科技学院', url: 'http://jwxt.syist.edu.cn:30334/jwapp/sys/emaphome/portal/index.do'),
    SchoolInfo(name: '青岛黄海学院', url: 'http://jwxt.qdhhc.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '南通大学', url: 'https://tdjw.ntu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '辽宁科技大学', url: 'https://ustl.jw.chaoxing.com/admin/login'),
    SchoolInfo(name: '兰州理工大学', url: 'https://jwxt.lut.edu.cn/'),
    SchoolInfo(name: '兰州大学', url: 'http://jwk.lzu.edu.cn/academic/common/security/login.jsp'),
    SchoolInfo(name: '中山大学', url: 'https://jwxt.sysu.edu.cn/'),
    SchoolInfo(name: '中山大学（研究生）', url: 'https://cms.sysu.edu.cn/'),
    SchoolInfo(name: '山西电子科技学院', url: 'https://sso.sxdzkj.edu.cn/sso-auth/#/login?service=https://jwxt.sxdzkj.edu.cn/caslogin'),
    SchoolInfo(name: '郑州汽车工程职业学院', url: 'https://cas.zzvcae.edu.cn/cas/login'),
    SchoolInfo(name: '辽宁大学', url: 'http://jwstudent.lnu.edu.cn/'),
    SchoolInfo(name: '湖南工程学院', url: 'http://jwcmis.hnie.edu.cn'),
    SchoolInfo(name: '重庆工程学院', url: 'https://i.cqie.edu.cn/'),
    SchoolInfo(name: '安徽财经大学', url: 'http://all.aufe.edu.cn'),
    SchoolInfo(name: '广州航海学院', url: 'http://jwx.gzmtu.edu.cn/jwglxt/kbcx/xskbcx_cxXskbcxIndex.html?gnmkdm=N2151&layout=default', type: 'jwglxt'),
    SchoolInfo(name: '西南大学', url: 'https://i.swu.edu.cn/'),
    SchoolInfo(name: '郑州大学', url: 'https://cas.s.zzu.edu.cn/cas/a/login?service=https%3A%2F%2Fjwxt.zzu.edu.cn%2Fstudent%2Fsso%2Flogin'),
    SchoolInfo(name: '常州大学', url: 'https://zmvpn.cczu.edu.cn/http/webvpndc2d086cb5b297c15e661687e73c1549/web_jxrw/cx_kb_xsgrkb.aspx'),
    SchoolInfo(name: '福州理工学院', url: 'http://oaa.fitedu.net/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '广西机电职业技术学院', url: 'https://sso.gxcme.edu.cn/login?service=https://nportal.gxcme.edu.cn/login'),
    SchoolInfo(name: '河南科技大学', url: 'https://vpn.haust.edu.cn'),
    SchoolInfo(name: '哈尔滨工程大学', url: 'https://jwgl.hrbeu.edu.cn/jwapp/sys/emaphome/portal/index.do'),
    SchoolInfo(name: '哈尔滨工程大学（研究生）', url: 'https://yjs.hrbeu.edu.cn/'),
    SchoolInfo(name: '哈尔滨工业大学（研究生）', url: 'http://yjsgl-hit-edu-cn.ivpn.hit.edu.cn:1080/xs/index'),
    SchoolInfo(name: '河北经贸大学', url: 'https://202-206-194-100.vpn.hueb.edu.cn:8118/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '聊城大学东昌学院', url: 'https://jw.lcudcc.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '临沂大学', url: 'https://sdp.lyu.edu.cn/https/webvpn3146b55e2aeee09087ebc4ebe6dbd770/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '绥化学院', url: 'http://jwgl.shxy.edu.cn/'),
    SchoolInfo(name: '三明学院', url: 'https://one.fjsmu.edu.cn/tp_up/view?m=up'),
    SchoolInfo(name: '南昌科技职业大学', url: 'http://jw.tellhowedu.com:19995/'),
    SchoolInfo(name: '西安交通大学', url: 'https://ehall.xjtu.edu.cn'),
    SchoolInfo(name: '青海师范大学（研究生）', url: 'http://one.qhnu.edu.cn/default/portal/index.jsp'),
    SchoolInfo(name: '武汉科技大学', url: 'https://bkjx.wust.edu.cn/jsxsd/framework/xsMain.jsp'),
    SchoolInfo(name: '南阳师范学院', url: 'https://vpn.nynu.edu.cn/'),
    SchoolInfo(name: '南昌航空大学', url: 'http://jwc-publish2.jwc.nchu.edu.cn/'),
    SchoolInfo(name: '河南理工大学', url: 'https://zhjw.hpu.edu.cn/eams/login.action'),
    SchoolInfo(name: '重庆航天职业技术学院', url: 'http://jw.cqepc.cn/'),
    SchoolInfo(name: '北京工商大学', url: 'https://jwgl.btbu.edu.cn/'),
    SchoolInfo(name: '华南师范大学', url: 'https://jwxt.scnu.edu.cn/xtgl/login_slogin.html'),
    SchoolInfo(name: '洛阳理工学院', url: 'https://lljw.lit.edu.cn/'),
    SchoolInfo(name: '安徽电气工程职业技术学院', url: 'https://zt.aepu.com.cn/http/webvpnae4cfe98f83bc8811cc5963452fd80627ab088b1bddf3f753580a56a75a714e9/ywtb-portal/official/index.html#/hall'),
    SchoolInfo(name: '南方科技大学', url: 'https://cas.sustech.edu.cn/cas/login?service=https%3A%2F%2Ftis.sustech.edu.cn%2Fcas'),
    SchoolInfo(name: '中国地质大学(武汉)', url: 'https://sfrz.cug.edu.cn/authserver/login?service=https%3A%2F%2Fi.cug.edu.cn%2Fweb%2F%3FCASLOGIN%3DCASLOGIN'),
    SchoolInfo(name: '中国地质大学(武汉)（研究生）', url: 'https://epo.cug.edu.cn'),
    SchoolInfo(name: '广州华立学院', url: 'https://jw.hualixy.edu.cn/sso/ddlogin'),
    SchoolInfo(name: '西安建筑科技大学', url: 'https://swjw.xauat.edu.cn/student/login/'),
    SchoolInfo(name: '徐州医科大学（研究生）', url: 'https://authserver.xzhmu.edu.cn/authserver/login?service=https%3A%2F%2Fehall.xzhmu.edu.cn%2Flogin'),
    SchoolInfo(name: '梧州职业学院', url: 'http://222.217.195.24:805/wzzyjw/cas/login.action'),
    SchoolInfo(name: '浙江树人学院', url: 'http://xk.jwc.zjsru.edu.cn/'),
    SchoolInfo(name: '江苏电子信息职业学院', url: 'https://ehall.jsei.edu.cn/new/index.html'),
    SchoolInfo(name: '江苏科技大学', url: 'https://my.just.edu.cn/'),
    SchoolInfo(name: '河南城建学院', url: 'http://jwglxt.huuc.edu.cn:8061/admin/login', type: 'jwglxt'),
    SchoolInfo(name: '南开大学（研究生）', url: 'https://yjs.nankai.edu.cn/py/page/student/grkcb.htm'),
    SchoolInfo(name: '大连理工大学', url: 'http://jxgl.dlut.edu.cn/student/for-std/course-table'),
    SchoolInfo(name: '曲阜师范大学', url: 'http://zhjw.qfnu.edu.cn/jsxsd/'),
    SchoolInfo(name: '四川机电职业技术学院', url: 'http://192.168.73.155/personal-center'),
    SchoolInfo(name: '福建师范大学（研究生）', url: 'https://gedu.fjnu.edu.cn/cas/login?service=https%3A%2F%2Fgedu.fjnu.edu.cn%2Findex'),
    SchoolInfo(name: '河南工程学院', url: 'http://106.system.haue.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '许昌学院', url: 'https://jwglxt.xcu.edu.cn/jwglxt/xtgl/login_slogin.html', type: 'jwglxt'),
    SchoolInfo(name: '广东科贸职业学院', url: 'https://aic.gdkm.edu.cn/cas_server/login'),
    SchoolInfo(name: '上海电力大学', url: 'https://jw.shiep.edu.cn/eams/index.action'),
    SchoolInfo(name: '上海师范大学', url: 'https://course.shnu.edu.cn/'),
    SchoolInfo(name: '东北林业大学', url: 'https://jwxt.nefu.edu.cn/jsxsd/'),
    SchoolInfo(name: '四川托普信息技术职业学院', url: 'http://zf.scetop.com/default2.aspx'),
    SchoolInfo(name: '湖南农业大学', url: 'https://webvpn.hunau.edu.cn/login?cas_login=true'),
    SchoolInfo(name: '山东财经大学燕山学院', url: 'https://ysjw.sdufe.edu.cn:8081/jsxsd/'),
    SchoolInfo(name: '南京信息职业技术学院', url: 'https://jw.njcit.cn/sso/lyiotlogin'),
    SchoolInfo(name: '泉州职业技术大学', url: 'https://jw.qvtu.edu.cn/jsxsd/'),
  ];
}
